from django.utils import timezone
import datetime as dt

"""
API entries
"""

three_shifts_third_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 800,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 3,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 6, 25)),
}

three_shifts_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 160,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 160,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 160,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 160,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 160,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 160,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 160,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 160,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 160,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 1600,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 16,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

three_shifts_second_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 240,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 240,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 240,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 240,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 240,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 240,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 240,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 240,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 240,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 2400,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 24,

    'shift': 2,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 22, 25)),
}

two_shifts_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 800,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

two_shifts_second_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 160,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 160,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 160,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 160,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 160,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 160,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 160,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 160,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 160,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 1600,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 16,

    'shift': 2,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 22, 25)),
}

one_shift_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 100,
    'PLANT_d_mh': 800,
    'PLANT_s_hpv': 100,
    'PLANT_s_ne': 100,
    'PLANT_s_mh': 800,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}


"""
Plant Settings
"""
default_plant_settings = {
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 7, 0)),
    'plant_code': '017',
    'plant_target': 55,
    'num_of_shifts': 2,
    'first_shift': dt.time(6,30),
    'second_shift': dt.time(14,30),
    'third_shift': dt.time(22,30),
    'dripper_start': timezone.make_aware(dt.datetime(2016, 6, 2, 8, 0))
}

three_shift_8_am_plant_settings = {
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 7, 0)),
    'plant_code': '017',
    'plant_target': 55,
    'num_of_shifts': 3,
    'first_shift': dt.time(6,30),
    'second_shift': dt.time(14,30),
    'third_shift': dt.time(22,30),
    'dripper_start': timezone.make_aware(dt.datetime(2016, 6, 2, 8, 0))
}

two_shift_8_am_plant_settings = {
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 7, 0)),
    'plant_code': '017',
    'plant_target': 55,
    'num_of_shifts': 2,
    'first_shift': dt.time(6,30),
    'second_shift': dt.time(14,30),
    'third_shift': dt.time(22,30),
    'dripper_start': timezone.make_aware(dt.datetime(2016, 6, 2, 8, 0))
}

one_shift_8_am_plant_settings = {
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 7, 0)),
    'plant_code': '017',
    'plant_target': 55,
    'num_of_shifts': 1,
    'first_shift': dt.time(6,30),
    'second_shift': dt.time(14,30),
    'third_shift': dt.time(22,30),
    'dripper_start': timezone.make_aware(dt.datetime(2016, 6, 2, 8, 0))
}


"""
HPV Dictionaries
"""
shift_1_hpv_dict = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 1, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}}

shift_1_hpv_dict_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 1, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}}

shift_1_hpv_dict_with_plant = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 1, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'plant_hpv': 100, 'plant_mh': 100,'plant_ne': 100,}

shift_1_hpv_dict_with_plant_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 1, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'plant_hpv': 0, 'plant_mh': 0, 'plant_ne': 0}

shift_2_hpv_dict = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 2, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}}

shift_2_hpv_dict_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 2, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}}

shift_2_hpv_dict_with_plant = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 2, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'plant_hpv': 100, 'plant_mh': 100,'plant_ne': 100,}

shift_2_hpv_dict_with_plant_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 2, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'plant_hpv': 0, 'plant_mh': 0, 'plant_ne': 0}

shift_3_hpv_dict = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 3, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}}

shift_3_hpv_dict_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 3, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}}

shift_3_hpv_dict_with_plant = {'QA': {'ne': 10, 'hpv': 10, 'mh': 10}, 'claims_for_range': 1, 'MAINT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PNT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'PLANT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'shift': 3, 'FCB': {'ne': 10, 'hpv': 10, 'mh': 10}, 'CIW': {'ne': 10, 'hpv': 10, 'mh': 10}, 'DAC': {'ne': 10, 'hpv': 10, 'mh': 10}, 'OTHER': {'ne': 0, 'hpv': 0, 'mh': 0}, 'FCH': {'ne': 10, 'hpv': 10, 'mh': 10}, 'MAT': {'ne': 10, 'hpv': 10, 'mh': 10}, 'plant_hpv': 100, 'plant_mh': 100,'plant_ne': 100}

shift_3_hpv_dict_with_plant_0_hpv = {'QA': {'ne': 0, 'hpv': 0, 'mh': 0}, 'claims_for_range': 0, 'MAINT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PNT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'PLANT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'shift': 3, 'FCB': {'ne': 0, 'hpv': 0, 'mh': 0}, 'CIW': {'ne': 0, 'hpv': 0, 'mh': 0}, 'DAC': {'ne': 0, 'hpv': 0, 'mh': 0}, 'OTHER': {'ne': 0, 'hpv': 0.0, 'mh': 0}, 'FCH': {'ne': 0, 'hpv': 0, 'mh': 0}, 'MAT': {'ne': 0, 'hpv': 0, 'mh': 0}, 'plant_hpv': 0, 'plant_mh': 0, 'plant_ne': 0}
