clock_in_out_csv = 'data/emp+item+punch.csv'
direct_run_csv = 'data/Direct_Run.csv'
item_shortages_csv = 'data/ITMSHORT(shortages).csv'
crys_csv = 'data/QAVHITDS(crys).csv'
shopcalls_csv = 'data/Shopcalls.csv'
plant_activty_csv = 'data/SV_PLANT_ACTY_DTL(Claims).csv'
departments_csv = 'data/3rd Shift Mount Holly Org Updates 2015 edited.csv'
