from django.utils import timezone
import datetime as dt

"""
API entries
"""
three_shifts_third_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 720,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 3,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 6, 25)),
}

three_shifts_third_shift_api_entry_0_claims = {
    'CIW_s_hpv': 0,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 0,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 0,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 0,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 0,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 0,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 0,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 0,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 0,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 0,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 0,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 0,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 0,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 0,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 0,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 0,
    'QA_d_mh': 80,
    'MAT_s_hpv': 0,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 0,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 0,
    'PLANT_d_mh': 720,
    'PLANT_s_hpv': 0,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 0,
    'claims_d': 0,

    'shift': 3,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 6, 25)),
}


three_shifts_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 160,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 160,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 160,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 160,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 160,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 160,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 160,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 160,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 160,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 1440,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 8,
    'claims_d': 16,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

three_shifts_first_shift_api_entry_0_claims = {
    'CIW_s_hpv': 0,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 0,
    'CIW_d_mh': 160,
    'FCB_s_hpv': 0,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 0,
    'FCB_d_mh': 160,
    'PNT_s_hpv': 0,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 0,
    'PNT_d_mh': 160,
    'PCH_s_hpv': 0,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 0,
    'PCH_d_mh': 160,
    'FCH_s_hpv': 0,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 0,
    'FCH_d_mh': 160,
    'DAC_s_hpv': 0,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 0,
    'DAC_d_mh': 160,
    'MAINT_s_hpv': 0,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 0,
    'MAINT_d_mh': 160,
    'QA_s_hpv': 0,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 0,
    'QA_d_mh': 160,
    'MAT_s_hpv': 0,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 0,
    'MAT_d_mh': 160,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 0,
    'PLANT_d_mh': 1440,
    'PLANT_s_hpv': 0,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 0,
    'claims_d': 0,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

three_shifts_second_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 240,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 240,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 240,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 240,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 240,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 240,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 240,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 240,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 240,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 2160,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 8,
    'claims_d': 24,

    'shift': 2,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 22, 25)),
}

two_shifts_first_shift_api_entry_7_am = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 5,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 5,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 5,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 5,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 5,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 5,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 5,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 5,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 5,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 5,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 5,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 5,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 5,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 5,
    'QA_s_hpv': 10,
    'QA_s_mh': 5,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 5,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 5,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 5,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 45,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 45,

    'claims_s': 1,
    'claims_d': 1,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 7, 0)),
}

two_shifts_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 720,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

two_shifts_first_shift_api_entry_0_claims = {
    'CIW_s_hpv': 0,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 0,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 0,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 0,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 0,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 0,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 0,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 0,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 0,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 0,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 0,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 0,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 0,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 0,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 0,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 0,
    'QA_d_mh': 80,
    'MAT_s_hpv': 0,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 0,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 0,
    'PLANT_d_mh': 720,
    'PLANT_s_hpv': 0,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 0,
    'claims_d': 0,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}

two_shifts_second_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 40,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 120,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 40,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 120,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 40,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 120,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 40,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 120,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 40,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 120,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 40,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 120,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 40,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 120,
    'QA_s_hpv': 10,
    'QA_s_mh': 40,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 120,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 40,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 120,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 1080,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 360,

    'claims_s': 8,
    'claims_d': 12,

    'shift': 2,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 18, 25)),
}

one_shift_first_shift_api_entry = {
    'CIW_s_hpv': 10,
    'CIW_s_mh': 80,
    'CIW_s_ne': 10,
    'CIW_d_hpv': 10,
    'CIW_d_mh': 80,
    'FCB_s_hpv': 10,
    'FCB_s_mh': 80,
    'FCB_s_ne': 10,
    'FCB_d_hpv': 10,
    'FCB_d_mh': 80,
    'PNT_s_hpv': 10,
    'PNT_s_mh': 80,
    'PNT_s_ne': 10,
    'PNT_d_hpv': 10,
    'PNT_d_mh': 80,
    'PCH_s_hpv': 10,
    'PCH_s_mh': 80,
    'PCH_s_ne': 10,
    'PCH_d_hpv': 10,
    'PCH_d_mh': 80,
    'FCH_s_hpv': 10,
    'FCH_s_mh': 80,
    'FCH_s_ne': 10,
    'FCH_d_hpv': 10,
    'FCH_d_mh': 80,
    'DAC_s_hpv': 10,
    'DAC_s_mh': 80,
    'DAC_s_ne': 10,
    'DAC_d_hpv': 10,
    'DAC_d_mh': 80,
    'MAINT_s_hpv': 10,
    'MAINT_s_mh': 80,
    'MAINT_s_ne': 10,
    'MAINT_d_hpv': 10,
    'MAINT_d_mh': 80,
    'QA_s_hpv': 10,
    'QA_s_mh': 80,
    'QA_s_ne': 10,
    'QA_d_hpv': 10,
    'QA_d_mh': 80,
    'MAT_s_hpv': 10,
    'MAT_s_mh': 80,
    'MAT_s_ne': 10,
    'MAT_d_hpv': 10,
    'MAT_d_mh': 80,
    'OTHER_s_hpv': 0,
    'OTHER_s_mh': 0,
    'OTHER_s_ne': 0,
    'OTHER_d_hpv': 0,
    'OTHER_d_mh': 0,

    'PLANT_d_hpv': 90,
    'PLANT_d_mh': 720,
    'PLANT_s_hpv': 90,
    'PLANT_s_ne': 90,
    'PLANT_s_mh': 720,

    'claims_s': 8,
    'claims_d': 8,

    'shift': 1,
    'timestamp': timezone.make_aware(dt.datetime(2016, 6, 2, 14, 25)),
}
