# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.6 on 2016-06-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.9.6 on 2016-06-03 14:52
from __future__ import unicode_literals

from django.db import migrations
>>>>>>> fc31b65ed1c5ed98b8c214d6f46547622f8a5a39


class Migration(migrations.Migration):

<<<<<<< HEAD
    initial = True

=======
>>>>>>> fc31b65ed1c5ed98b8c214d6f46547622f8a5a39
    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
        migrations.CreateModel(
            name='OrgUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_abrv', models.CharField(max_length=5)),
                ('dept_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawClockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRSN_NBR_TXT', models.CharField(max_length=100)),
                ('full_nam', models.TextField()),
                ('HM_LBRACCT_FULL_NAM', models.TextField()),
                ('start_rsn_txt', models.CharField(max_length=100)),
                ('PNCHEVNT_IN', models.DateTimeField(null=True)),
                ('end_rsn_txt', models.CharField(max_length=100)),
                ('PNCHEVNT_OUT', models.DateTimeField(null=True)),
            ],
        ),
=======
>>>>>>> fc31b65ed1c5ed98b8c214d6f46547622f8a5a39
    ]
