# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockData',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('plant_id', models.IntegerField(choices=[(17, 'MTH')])),
                ('dept_id', models.IntegerField()),
                ('shift', models.IntegerField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
                ('clock_in_flag', models.CharField(max_length=255)),
                ('clock_out_flag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_abrv', models.CharField(max_length=5)),
                ('dept_id', models.CharField(max_length=100)),
                ('shift_id', models.CharField(max_length=10)),
            ],
        ),
    ]
