# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:09

from __future__ import unicode_literals
from django.db import migrations
import csv


def get_categories(apps, schema_editor):
    Department = apps.get_model("get_data", "OrgUnits")
    with open('data/3rd Shift Mount Holly Org Updates 2015 edited.csv') as f:
        next(f)
        next(f)
        next(f)
        data = csv.reader(f)
        for row in data:
            department = Department(dept_name=row[1], dept_abrv=row[2],
                                    dept_id=row[3], shift_id=row[5])
            department.save()


class Migration(migrations.Migration):
    dependencies = [
        ('get_data', '0002_clockdata_orgunits'),
        ]
    operations = [
        migrations.RunPython(get_categories),
        ]
